"""Bake Natural Earth's land polygons into an equirectangular land/sea bitmask.

The globe draws its continents as dots scattered over the sphere, which needs
one question answered a few thousand times at startup: is this lat/lng on land?
A raster mask answers it in constant time, so the polygons themselves never
ship — only 16KB of packed bits.

Source: Natural Earth 110m physical land (public domain, no attribution
required). Download it next to this script before running:

    curl -sSLo ne_110m_land.json \\
      https://raw.githubusercontent.com/martynafford/natural-earth-geojson/master/110m/physical/ne_110m_land.json
    python3 gen-landmask.py

Rasterising is an even-odd scanline fill: for each pixel row, collect every
edge crossing that row, sort the crossings, and fill between alternate pairs.
Even-odd falls out of GeoJSON's ring convention for free — an inner ring (the
Caspian, say) reverses parity over its span and punches its own hole.
"""

import base64
import json
import os

WIDTH = 512
HEIGHT = 256

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "ne_110m_land.json")
OUT = os.path.join(HERE, "..", "src", "globe", "landMask.ts")


def rings(geojson):
    """Every linear ring in the file, as flat lists of (lon, lat)."""
    out = []
    for feature in geojson["features"]:
        geom = feature["geometry"]
        kind = geom["type"]
        if kind == "Polygon":
            polygons = [geom["coordinates"]]
        elif kind == "MultiPolygon":
            polygons = geom["coordinates"]
        else:
            continue
        for polygon in polygons:
            for ring in polygon:
                if len(ring) >= 3:
                    out.append(ring)
    return out


def to_pixels(ring):
    """Lon/lat degrees -> pixel space, y flipped so row 0 is the north pole."""
    return [
        ((lon + 180.0) / 360.0 * WIDTH, (90.0 - lat) / 180.0 * HEIGHT)
        for lon, lat in ring
    ]


def rasterise(all_rings):
    """Even-odd scanline fill over every ring at once."""
    mask = bytearray(WIDTH * HEIGHT)
    edges = []
    for ring in all_rings:
        pts = to_pixels(ring)
        for i in range(len(pts)):
            x0, y0 = pts[i]
            x1, y1 = pts[(i + 1) % len(pts)]
            if y0 != y1:  # horizontal edges never cross a scanline centre
                edges.append((x0, y0, x1, y1))

    for row in range(HEIGHT):
        yc = row + 0.5
        crossings = []
        for x0, y0, x1, y1 in edges:
            # half-open in y so a vertex shared by two edges counts once
            if (y0 <= yc < y1) or (y1 <= yc < y0):
                t = (yc - y0) / (y1 - y0)
                crossings.append(x0 + t * (x1 - x0))
        if not crossings:
            continue
        crossings.sort()
        base = row * WIDTH
        for i in range(0, len(crossings) - 1, 2):
            start = max(0, int(crossings[i] + 0.5))
            end = min(WIDTH, int(crossings[i + 1] + 0.5))
            for col in range(start, end):
                mask[base + col] = 1
    return mask


def pack(mask):
    """One bit per pixel, MSB first, row-major."""
    packed = bytearray((WIDTH * HEIGHT + 7) // 8)
    for i, v in enumerate(mask):
        if v:
            packed[i >> 3] |= 0x80 >> (i & 7)
    return bytes(packed)


def main():
    with open(SOURCE) as fh:
        geojson = json.load(fh)

    all_rings = rings(geojson)
    mask = rasterise(all_rings)
    packed = pack(mask)

    land = sum(mask)
    total = WIDTH * HEIGHT
    # Equirectangular over-weights the poles, so area-weight by cos(lat) to get
    # a figure comparable with the real 29%.
    import math

    weighted = weighted_total = 0.0
    for row in range(HEIGHT):
        lat = 90.0 - (row + 0.5) / HEIGHT * 180.0
        w = math.cos(math.radians(lat))
        base = row * WIDTH
        weighted += w * sum(mask[base : base + WIDTH])
        weighted_total += w * WIDTH

    print(f"rings          {len(all_rings)}")
    print(f"raster         {WIDTH}x{HEIGHT}")
    print(f"land pixels    {land}/{total} ({land / total * 100:.1f}% of the raster)")
    print(f"land by area   {weighted / weighted_total * 100:.1f}%  (Earth is ~29%)")
    print(f"packed         {len(packed)} bytes -> {len(base64.b64encode(packed))} base64")

    b64 = base64.b64encode(packed).decode("ascii")
    chunks = [b64[i : i + 96] for i in range(0, len(b64), 96)]
    body = "\n".join(f"  '{c}' +" for c in chunks)
    body = body.rstrip(" +")

    ts = f'''// GENERATED by scripts/gen-landmask.py — do not edit by hand.
//
// Natural Earth 110m physical land, rasterised to a {WIDTH}x{HEIGHT}
// equirectangular 1-bit mask and packed MSB-first, row-major. Public domain:
// Natural Earth asks for no attribution and places no restrictions on use.
//
// Row 0 is the north pole, column 0 is 180°W.

export const LAND_MASK_WIDTH = {WIDTH}
export const LAND_MASK_HEIGHT = {HEIGHT}

const PACKED =
{body}

// Decoded once at module load: {len(packed)} bytes, cheaper to keep than to re-derive.
const BITS = /*@__PURE__*/ (() => {{
  const binary = atob(PACKED)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return bytes
}})()

/** True where the given coordinate falls on land. */
export function isLand(lat: number, lng: number): boolean {{
  // wrap longitude, clamp latitude — callers sampling a sphere hit the poles
  const x = Math.floor(((((lng + 180) % 360) + 360) % 360) / 360 * LAND_MASK_WIDTH)
  const yRaw = Math.floor(((90 - lat) / 180) * LAND_MASK_HEIGHT)
  const y = yRaw < 0 ? 0 : yRaw >= LAND_MASK_HEIGHT ? LAND_MASK_HEIGHT - 1 : yRaw
  const i = y * LAND_MASK_WIDTH + x
  return (BITS[i >> 3] & (0x80 >> (i & 7))) !== 0
}}
'''

    with open(OUT, "w") as fh:
        fh.write(ts)
    print(f"wrote          {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
